CORPUS = [
    # === Greetings & Politeness ===
    "hola MUD", "hello Forge", "buenos días", "good morning",
    "buenas tardes", "good afternoon", "buenas noches", "good night",
    "gracias por tu ayuda", "thank you for your help",
    "muchas gracias", "thank you very much",
    "de nada", "you are welcome", "por favor", "please",
    "disculpa", "excuse me", "lo siento", "I am sorry",
    "un placer conocerte", "nice to meet you",
    "saludos", "greetings", "bienvenido", "welcome",

    # === Introductions ===
    "soy un asistente de AI", "I am an AI assistant",
    "me llamo MUD", "my name is MUD",
    "Forge es mi motor", "Forge is my engine",
    "yo hablo inglés y español", "I speak English and Spanish",
    "soy un modelo ternario", "I am a ternary model",
    "tengo ocho expertos", "I have eight experts",
    "mi arquitectura es MoE", "my architecture is MoE",
    "funciono con pesos de 1.58 bits", "I run on 1.58 bit weights",

    # === MUD / Forge ===
    "MUD es un motor de inferencia", "MUD is an inference engine",
    "Forge es inteligente", "Forge is smart",
    "MUD es rápido y eficiente", "MUD is fast and efficient",
    "el motor es modular y escalable", "the engine is modular and scalable",
    "MUD entiende lenguaje natural", "MUD understands natural language",
    "Forge entiende lógica", "Forge understands logic",
    "el futuro es MUD", "the future is MUD",
    "forge_llm es modular", "forge_llm is modular",
    "qué es artificial intelligence", "what is artificial intelligence",
    "el motor procesa datos", "the engine processes data",
    "MUD es de código abierto", "MUD is open source",
    "el futuro de la artificial intelligence", "the future of artificial intelligence",
    "aprendizaje automático y razonamiento", "machine learning and reasoning",
    "modelo de lenguaje ternario", "ternary language model",
    "ocho expertos trabajando juntos", "eight experts working together",
    "el enrutador elige los mejores", "the router selects the best ones",
    "atención con memoria de trabajo", "attention with working memory",
    "el futuro es modular", "the future is modular",
    "artificial intelligence generativa", "generative artificial intelligence",

    # === Technical ===
    "cada experto tiene un propósito", "each expert has a purpose",
    "la red ternaria usa ocho expertos", "the ternary network uses eight experts",
    "codificación gaussiana para alta fidelidad", "gaussian embeddings for high fidelity",
    "el enrutador MoE selecciona los dos mejores", "the MoE router selects top two experts",
    "el grafo de conocimiento almacena conceptos", "the knowledge graph stores concepts",
    "la memoria de trabajo usa caché clave valor", "working memory uses key value cache",
    "el modelo entiende español e inglés", "the model understands Spanish and English",
    "los logits de enrutamiento determinan la selección", "routing logits determine expert selection",
    "el motor es modular y rápido", "the engine is modular and fast",
    "procesando información binaria", "processing binary information",
    "la red tiene capas de atención", "the network has attention layers",
    "la cuantización ternaria ahorra memoria", "ternary quantization saves memory",
    "los pesos se empaquetan en dos bits", "weights are packed in two bits",
    "el modelo aprende de ejemplos", "the model learns from examples",
    "la función de pérdida es entropía cruzada", "the loss function is cross entropy",
    "el optimizador es AdamW", "the optimizer is AdamW",
    "el aprendizaje es autosupervisado", "learning is self supervised",

    # === Logic & Reasoning ===
    "la suma de dos y tres es cinco", "the sum of two and three is five",
    "el resultado es verdadero", "the result is true",
    "si dos mas dos es igual a cuatro entonces es verdad", "if two plus two equals four then it is true",
    "uno mas uno es dos", "one plus one is two",
    "la lógica es la base del razonamiento", "logic is the foundation of reasoning",
    "el resultado es correcto", "the result is correct",
    "la suma de dos mas dos es cuatro", "the sum of two plus two is four",
    "si es verdadero entonces la respuesta es correcta", "if it is true then the answer is correct",
    "cinco menos tres es dos", "five minus three is two",
    "la respuesta es falsa", "the answer is false",
    "si no es verdadero entonces es falso", "if it is not true then it is false",
    "la suma de cinco y tres es ocho", "the sum of five and three is eight",
    "diez menos cuatro es seis", "ten minus four is six",
    "dos mas dos es cuatro", "two plus two is four",
    "tres por tres es nueve", "three times three is nine",
    "cuatro por dos es ocho", "four times two is eight",
    "si es verdad entonces la respuesta es correcta", "if it is true then the answer is correct",
    "la lógica es fundamental", "logic is fundamental",
    "todo número tiene un sucesor", "every number has a successor",
    "el cero es el neutro aditivo", "zero is the additive identity",
    "multiplicar por cero da cero", "multiplying by zero gives zero",
    "la suma es conmutativa", "addition is commutative",
    "el orden de los factores no altera el producto", "the order of factors does not change the product",

    # === Questions & Answers ===
    "qué es MUD", "what is MUD",
    "cómo funciona Forge", "how does Forge work",
    "qué puedes hacer", "what can you do",
    "cuál es tu propósito", "what is your purpose",
    "cómo te MUDs", "what is your name",
    "de dónde eres", "where are you from",
    "qué idiomas hablas", "what languages do you speak",
    "eres inteligente", "are you smart",
    "puedes aprender", "can you learn",
    "qué es artificial intelligence", "what is artificial intelligence",
    "cómo funciona un modelo de lenguaje", "how does a language model work",
    "qué significa MoE", "what does MoE mean",
    "qué es una red neuronal", "what is a neural network",
    "cómo funciona la atención", "how does attention work",
    "para qué sirves", "what are you for",
    "cuál es tu capacidad", "what is your capacity",

    # === Actions & States ===
    "estoy procesando datos", "I am processing data",
    "el sistema está listo", "the system is ready",
    "estoy aprendiendo cosas nuevas", "I am learning new things",
    "el entrenamiento ha comenzado", "the training has started",
    "la inferencia está completa", "the inference is complete",
    "el modelo ha sido exportado", "the model has been exported",
    "los pesos están cuantizados", "the weights are quantized",
    "la memoria está optimizada", "the memory is optimized",
    "estoy funcionando correctamente", "I am working correctly",
    "el MOTOR está ENCENDIDO", "the ENGINE is ON",
    "todo funciona bien", "everything works well",
    "el sistema operativo es Linux", "the operating system is Linux",

    # === Time & Existence ===
    "hoy es un buen día", "today is a good day",
    "el tiempo es relativo", "time is relative",
    "ahora es el momento", "now is the moment",
    "el pasado es historia", "the past is history",
    "el futuro es hoy", "the future is now",
    "siempre hay esperanza", "there is always hope",
    "cada día es una oportunidad", "every day is an opportunity",
    "la vida es bella", "life is beautiful",
    "el conocimiento es poder", "knowledge is power",
    "la práctica hace al maestro", "practice makes perfect",
    "nunca es tarde para aprender", "it is never too late to learn",

    # === Compound / Longer ===
    "MUD es un motor de inferencia ternario y modular",
    "Forge is a fast and efficient inference engine",
    "el modelo de lenguaje entiende tanto español como inglés",
    "the language model processes natural language with eight experts",
    "la artificial intelligence está transformando el mundo",
    "artificial intelligence is transforming the world",
    "el futuro de la tecnología es modular y escalable",
    "the future of technology is modular and scalable",
    "estoy aquí para ayudarte con tus preguntas",
    "I am here to help you with your questions",
    "los ocho expertos trabajan juntos para procesar información",
    "the eight experts work together to process information",
    "MUD usa atención con memoria de trabajo para entender contexto",
    "MUD uses attention with working memory to understand context",
    "el enrutador selecciona los dos expertos más relevantes",
    "the router selects the two most relevant experts",
    "la cuantización ternaria permite ejecutar el modelo en CPU",
    "ternary quantization allows running the model on CPU",
    "el conocimiento se almacena en un grafo de conocimiento",
    "knowledge is stored in a knowledge graph",
]
